### ISSUE TITLE
Importing

### ISSUE THREAD

**Issue by resumenj** [rpraka/ChartATM#1]
Ty for the code! much appreciated
Don't know why I am getting this error when I import the file into NT8

![Screenshot 2022-04-23 102436](https://user-images.githubusercontent.com/99693698/164910109-cf5e7601-92c5-493d-b2ba-8890fcec2159.png)

**Comment by rpraka** [comment]
Hey, thanks for your interest in the project. Try the 4th method at the link [here](https://futures.io/articles/trading/How-to-import-indicators-in-NinjaTrader). Sometimes NT fails to automatically import the zip folder if you have other custom indicators installed.

**Comment by resumenj** [comment]
Thanks it worked! My daughter is a developer and she does not help me :(

**Comment by resumenj** [comment]
Hi Is there a way to add right click mouse to buy for the resistance breakout and sell if price breaks the support
